global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.office365.com:587'
  smtp_from: 'support@n7banking.com'
  http_config:
    tls_config:
      insecure_skip_verify: true

route:
  group_by: ['severity','alertname']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 30m
  receiver: "email"

  routes:
    - receiver: "teams"
      group_wait: 10s
      match_re:
        severity: critical|warning|high
      continue: true

    - receiver: "email"
      group_wait: 10s
      match_re:
        severity: critical
      continue: true

# route:
#   group_by: [ alertname ]
#   receiver: 'mail' # default receiver
#   repeat_interval: 24h
#   routes:
#     - receiver: 'teams'
#       repeat_interval: 10s
#       matchers:
#         - severity="medium"

#     - receiver: 'teams'
#       repeat_interval: 10s
#       matchers:
#         - severity="high"



  # - name: 'mail'
  #   email_configs:
  #     - smarthost: 'smtp.office365.com:587'
  #       auth_username: 'support@n7banking.com'
  #       auth_password: ""
  #       from: 'support@n7banking.com'
  #       to: 'prasath.s@neuralrays.ai,krishna.k@neuralrays.ai,Prathap.KVB@NeuralRays.AI'
  #       require_tls: true
receivers:
  - name: "email"
    email_configs:
      - to: 'prasath.s@neuralrays.ai,krishna.k@neuralrays.ai,Prathap.KVB@NeuralRays.AI,Pradeepkumar.A@NeuralRays.AI'
        send_resolved: true
        auth_username: 'support@n7banking.com'
        auth_identity: 'support@n7banking.com'
        auth_password: 'password'

  - name: 'teams'
    webhook_configs:
      - url: "http://prom2teams:8089"
        send_resolved: true