route:
  group_by: [ alertname ]
  receiver: 'mail' # default receiver
  repeat_interval: 24h

receivers: 
  - 
    name: prometheus-msteams
    webhook_configs: 
      - 
        send_resolved: true
        url: "http://prometheus-msteams:2000/alertmanager"
route: 
  group_interval: 5m
  group_wait: 30s
  receiver: prometheus-msteams
  repeat_interval: 12h

  
receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'smtp.office365.com:465'
        auth_username: 'support@n7banking.com'
        auth_password: ""
        from: 'support@n7banking.com'
        to: 'prasath.s@neuralrays.ai,krishna.k@neuralrays.ai,Prathap.KVB@NeuralRays.AI'
        require_tls: false

inhibit_rules:
    - source_match:
        severity: critical
    - target_match:
        severity: warning
    - equal: ['alertname', 'dev', 'instance']