global:
  resolve_timeout: 1m

route:
  group_by: ['severity','alertname']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1m
  receiver: "email"

  routes:
    - receiver: "teams"
      group_wait: 10s
      match_re:
        severity: low|warning|high
      continue: true

    - receiver: "email"
      group_wait: 10s
      match_re:
        severity: low|warning|high
      continue: true

receivers:
  - name: "email"
    email_configs:
      - to: 'prasath.s@neuralrays.ai,krishna.k@neuralrays.ai,Prathap.KVB@NeuralRays.AI,Pradeepkumar.A@NeuralRays.AI'
        send_resolved: true
        auth_username: 'support@n7banking.com'
        auth_identity: 'support@n7banking.com'
        auth_password: 'password'
        send_resolved: true

  - name: 'teams'
    webhook_configs:
      - url: "http://prom2teams:8089"
        send_resolved: true

