version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.30.3
    user: root
    container_name: prometheus
    ports:
      - 9090:9090
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus-data:/prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana:8.2.2 
    user: 1000:1000
    container_name: grafana
    ports:
      - 9091:3000
    restart: always
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false

  cadvisor:
    image: 'google/cadvisor:latest'
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk:/dev/disk/:ro    
    ports:
      - 9092:8080 
    restart: always        

  alertmanager:
    image: prom/alertmanager:v0.23.0
    container_name: alertmanager
    restart: always
    ports:
      - 9093:9093
    volumes:
      - "./alertmanager:/config"
      - ./alertmanager-data:/data
    command: --config.file=/config/alertmanager.yml --log.level=debug 

  loki:
    image: grafana/loki:2.5.0
    ports:
      - 9094:3100
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.5.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
  node-exporter:
    image: "prom/node-exporter"
    ports:
      - 9100:9100
    restart: always
 
  caddy:
    image: stefanprodan/caddy
    container_name: caddy
    volumes:
      - ./caddy:/etc/caddy
    environment:
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: unless-stopped

  prometheus-msteams:
    image: docker.io/bzon/prometheus-msteams:v1.1.4
    container_name: prometheus-msteams
    restart: unless-stopped
    environment:
        - TEAMS_INCOMING_WEBHOOK_URL=https://neuralraysai.webhook.office.com/webhookb2/a91155c5-c398-4649-bab1-da10644314ba@76015437-c81b-4212-bb16-d81ed693aa5f/IncomingWebhook/d76c15bf214a4cb9be0ddae0a019515b/69878b73-495f-4303-beda-057f94271ee9
        - TEAMS_REQUEST_URI=alertmanager    
networks:
  default:
      name: devops