global:
  scrape_interval: 15s
  scrape_timeout: 15s

rule_files:
  - alert.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
  - job_name: grafana
    static_configs:
      - targets: 
          - 'grafana:3000'
  - job_name: 'config-jmx'
    static_configs:
      - targets:
          - 'config:10254'
  - job_name: 'DEV-Service'
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - ['master:8080','account:8080','admin:8080','login:8080','central:8080','customer:8080','gateway:8080','report:8080','transaction:8080']     
  - job_name: cadvisor
    static_configs:
      - targets:
          - 'cadvisor:8080'       

  - job_name: 'QA-master'
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets:
          - '10.0.1.11:9011'     
        labels:
          group: 'qa'                       
