global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
  - job_name: grafana
    static_configs:
      - targets: 
          - 'grafana:3000'
  - job_name: 'config-jmx'
    static_configs:
      - targets:
          - 'config:10254'
  - job_name: 'microservices'
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'master:8080'
  - job_name: cadvisor
    static_configs:
      - targets:
          - 'cadvisor:8080'
  - job_name: 'ContainerDown'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'admin:8080'
          - 'account:8080'
          - 'central:8080'
          - 'config:8080'
          - 'customer:8080'
          - 'digital:8080'
          - 'frontend:3100'
          - 'gateway:8080'
          - 'login:8080'
          - 'master:8080' 
          - 'report:8080'
          - 'servicediscovery::8761'
          - 'transcation:8080'         

                
